namespace LOTR_GameRegister.Domain.Models.Entities
{
    /// <summary>
    /// Represents a single recorded game of the Lord of the Rings: The Card Game.
    /// </summary>
    public class Game
    {
        /// <summary>
        /// Unique identifier of the game (auto-generated by the database).
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Date on which the game was played.
        /// </summary>
        public DateOnly DatePlayed { get; set; }

        /// <summary>
        /// Whether the game was played as part of a campaign mode.
        /// </summary>
        public bool IsCampaignMode { get; set; }

        /// <summary>
        /// Identifier of the quest (scenario) played in the game.
        /// </summary>
        public int QuestId { get; set; }

        /// <summary>
        /// Identifier of the difficulty level the game was played at.
        /// </summary>
        public int DifficultyId { get; set; }

        /// <summary>
        /// Number of spheres used by the heroes in that game.
        /// </summary>
        public int Spheres { get; set; }

        /// <summary>
        /// Number of heroes that died during the game.
        /// </summary>
        public int DeadHeroes { get; set; }

        /// <summary>
        /// Identifier of the game outcome (win, loss or surrender).
        /// </summary>
        public int ResultId { get; set; }

        /// <summary>
        /// Identifier of the reason for defeat, when the game was lost.
        /// </summary>
        public int? ReasonForDefeatId { get; set; }

        /// <summary>
        /// Free-text notes about the game.
        /// </summary>
        public string? Notes { get; set; }

        /// <summary>
        /// Heroes used in the game, linked through the GameHeroes join table (carries whether each hero died).
        /// </summary>
        public List<Hero> Heroes { get; set; } = new List<Hero>();

        /// <summary>
        /// Recomputes derived values that depend only on the game's own state.
        /// </summary>
        public void Recalculate()
        {
            DeadHeroes = Heroes?.Count(hero => hero.IsDead) ?? 0;
        }
    }
}
