namespace LOTR_GameRegister.Domain.Models.Entities
{
    /// <summary>
    /// Represents a registered user account of the register.
    /// </summary>
    public class User
    {
        /// <summary>
        /// Unique identifier of the user (auto-generated by the database).
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Username used to log in.
        /// </summary>
        public string Username { get; set; } = string.Empty;

        /// <summary>
        /// Email address of the user.
        /// </summary>
        public string Email { get; set; } = string.Empty;

        /// <summary>
        /// BCrypt hash of the user's password.
        /// </summary>
        public string PasswordHash { get; set; } = string.Empty;

        /// <summary>
        /// Role of the user (e.g. "Admin" or "Player"), used for authorization.
        /// </summary>
        public string Role { get; set; } = "Player";

        /// <summary>
        /// Date and time (UTC) at which the account was created.
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Games the user has played.
        /// </summary>
        public List<Game> Games { get; set; } = [];
    }
}
